; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Arduino Mega 2560 en COM4
[env:megaatmega1280]
platform = atmelavr
board = megaatmega2560
framework = arduino
upload_port = COM4
upload_speed = 115200
upload_protocol = wiring
monitor_port = COM4
monitor_speed = 115200
